name: Medical Documents Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT: 3001

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-test.txt ]; then
            pip install -r requirements-test.txt
          else
            echo "Error: requirements-test.txt not found"
            exit 1
          fi

      - name: Create test directories
        run: |
          mkdir -p test-results
          mkdir -p playwright-report
          mkdir -p .next/logs

      - name: Install Playwright browsers
        run: playwright install --with-deps chromium

      - name: Build Next.js application
        run: npm run build
        env:
          PORT: 3001

      - name: Start Next.js server
        run: |
          echo "Starting Next.js server..."
          # Redirect server output to log file
          npm run start -p 3001 > .next/logs/server.log 2>&1 &
          echo "Waiting for server to be ready..."
          timeout 30s bash -c 'while ! nc -z localhost 3001; do 
            echo "Waiting for port 3001..."
            sleep 1
          done' || (echo "Server failed to start" && exit 1)
          echo "Server is ready!"
        env:
          PORT: 3001

      - name: Run tests
        run: |
          echo "Running tests..."
          pytest tests/test_medical_page.py -v --html=test-results/report.html
        env:
          PORT: 3001
          PLAYWRIGHT_BASE_URL: "http://localhost:3001"

      - name: Prepare artifacts
        if: always()
        run: |
          # Create a summary file
          echo "Test Summary" > test-results/summary.txt
          echo "============" >> test-results/summary.txt
          echo "Date: $(date)" >> test-results/summary.txt
          echo "Branch: ${{ github.ref }}" >> test-results/summary.txt
          
          # Copy server logs if they exist
          if [ -f .next/logs/server.log ]; then
            cp .next/logs/server.log test-results/
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/
          if-no-files-found: warn 