name: Medical Documents Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT: 3001

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-test.txt ]; then
            pip install -r requirements-test.txt
          else
            echo "Error: requirements-test.txt not found"
            exit 1
          fi

      - name: Install Playwright browsers
        run: playwright install --with-deps chromium

      - name: Build Next.js application
        run: npm run build
        env:
          PORT: 3001

      - name: Start Next.js server
        run: |
          echo "Starting Next.js server..."
          npm run start -p 3001 &
          echo "Waiting for server to be ready..."
          timeout 30s bash -c 'while ! nc -z localhost 3001; do 
            echo "Waiting for port 3001..."
            sleep 1
          done' || (echo "Server failed to start" && exit 1)
          echo "Server is ready!"
        env:
          PORT: 3001

      - name: Run tests
        run: |
          echo "Running tests..."
          pytest tests/test_medical_page.py -v
        env:
          PORT: 3001
          PLAYWRIGHT_BASE_URL: "http://localhost:3001"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/
            
      - name: Upload server logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: server-logs
          path: .next/server.log 